### ISSUE TITLE
Criar documentação.

### ISSUE THREAD

**Issue by mpgxc** [eureka-sun/Elixir-Study#1]
Colocar no **readme**

- [x]  Objetivos
- [x]  Conteúdos
- [x] Fonte dos Conteúdos - **elixirschool**
- [x]  Regras
- [x]  E passo-a-passo de como contribuir, utilizar padrão da **Rocketseat**

**Comment by mpgxc** [comment]
Acho que tá completo, certo?

**Comment by daviluis321** [comment]
Sim,vou fechar essa issue

**Comment by daviluis321** [comment]
/
